//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Assembly
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssemblyBay
    {
        public int ConveyorID { get; set; }
        public int SectionID { get; set; }
        public int SlotLow { get; set; }
        public int SlotHigh { get; set; }
        public int MaxPieces { get; set; }
        public bool EnableTTS { get; set; }
    }
}
