//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Assembly
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssemAutoNumber
    {
        public int NextInvoiceID { get; set; }
        public int NextInvDetailID { get; set; }
        public int NextQueueID { get; set; }
        public int NextInvAssembledID { get; set; }
        public int NextStorageID { get; set; }
        public int NextAlertID { get; set; }
    }
}
