//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Assembly
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssemblyEntities1 : DbContext
    {
        public AssemblyEntities1()
            : base("name=AssemblyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alert> Alerts { get; set; }
        public virtual DbSet<AssemAutoNumber> AssemAutoNumbers { get; set; }
        public virtual DbSet<AssemblyBay> AssemblyBays { get; set; }
        public virtual DbSet<AssemblySetting> AssemblySettings { get; set; }
        public virtual DbSet<AutoSort> AutoSorts { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoicesAssembled> InvoicesAssembleds { get; set; }
        public virtual DbSet<InvoicesTest> InvoicesTests { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<StorageInvoice> StorageInvoices { get; set; }
        public virtual DbSet<Version> Versions { get; set; }
    }
}
