//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Assembly
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoSort
    {
        public int InvoiceID { get; set; }
        public int StoreID { get; set; }
        public int CustomerID { get; set; }
        public string StoreInvoiceID { get; set; }
        public string PieceTotal { get; set; }
        public string ItemNumber { get; set; }
        public string ArticleCode { get; set; }
        public string Description { get; set; }
        public string OccPercent { get; set; }
        public string Hung { get; set; }
        public string Status { get; set; }
        public string Conveyor { get; set; }
        public string Slot { get; set; }
        public string Out { get; set; }
        public string Customer { get; set; }
        public string RFID { get; set; }
        public string Arm { get; set; }
        public int Queue { get; set; }
        public int State { get; set; }
        public int Remaining { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string HomePhone { get; set; }
        public int BaySection { get; set; }
        public string BagLabel1 { get; set; }
        public string BagLabel2 { get; set; }
        public string BagLabel3 { get; set; }
        public string BagLabel4 { get; set; }
        public string BagLabel5 { get; set; }
        public string BagLabel6 { get; set; }
        public bool UseBAMStorage { get; set; }
        public int SubOut { get; set; }
        public string FlagTag { get; set; }
        public string BagLabel7 { get; set; }
        public string BagLabel8 { get; set; }
        public string BagLabel9 { get; set; }
        public string BagLabel10 { get; set; }
        public string BagLabel11 { get; set; }
        public string BagLabel12 { get; set; }
    }
}
