//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Assembly
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int StoreID { get; set; }
        public int CustomerID { get; set; }
        public int InvoiceID { get; set; }
        public int GarmentID { get; set; }
        public int DetailType { get; set; }
        public string DetailDesc { get; set; }
        public int Quantity { get; set; }
        public float Pieces { get; set; }
        public decimal Amount { get; set; }
        public bool Deleted { get; set; }
        public int InvDetailID { get; set; }
        public bool Voided { get; set; }
        public float AssemblyPieces { get; set; }
        public string ArticleCode { get; set; }
        public string FlagTag { get; set; }
        public string DetailGuid { get; set; }
    }
}
