//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Assembly
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicesAssembled
    {
        public int InvAssembledID { get; set; }
        public int StoreID { get; set; }
        public int CustomerID { get; set; }
        public int InvoiceID { get; set; }
        public int AssemblyInvoiceID { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string CustomerName { get; set; }
        public string Department { get; set; }
        public string SlotUsed { get; set; }
        public bool Deleted { get; set; }
        public int ConveyorID { get; set; }
    }
}
