//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Assembly
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int SlotID { get; set; }
        public int ConveyorID { get; set; }
        public int StoreID { get; set; }
        public int CustomerID { get; set; }
        public int InvoiceID { get; set; }
        public bool InUse { get; set; }
    }
}
