//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Assembly
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageInvoice
    {
        public int StorageID { get; set; }
        public int StoreID { get; set; }
        public int InvoiceID { get; set; }
        public int CustomerID { get; set; }
        public int DeliveryCustomerID { get; set; }
        public int BillCustomerID { get; set; }
        public Nullable<System.DateTime> RackDate { get; set; }
        public string Slot { get; set; }
        public int State { get; set; }
        public bool Deleted { get; set; }
    }
}
