//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoNumber
    {
        public Nullable<int> NextStoreID { get; set; }
        public Nullable<int> NextGLAccountID { get; set; }
        public Nullable<int> NextTaxID { get; set; }
        public Nullable<int> NextOrderID { get; set; }
        public Nullable<int> NextInvoiceID { get; set; }
        public Nullable<int> NextPaymentID { get; set; }
        public Nullable<int> NextClerkDrawerID { get; set; }
        public Nullable<int> NextNoSaleID { get; set; }
        public Nullable<int> NextCreditID { get; set; }
        public Nullable<int> NextCustID { get; set; }
        public long NextHeatSealID { get; set; }
        public Nullable<int> NextControl1 { get; set; }
        public Nullable<int> NextControl2 { get; set; }
        public Nullable<int> NextControl3 { get; set; }
        public Nullable<int> NextControl4 { get; set; }
        public Nullable<int> NextLotID { get; set; }
        public Nullable<int> NextLogId { get; set; }
        public Nullable<int> NextTimeCardID { get; set; }
        public Nullable<int> NextBilledID { get; set; }
        public Nullable<int> NextInvDetailID { get; set; }
        public Nullable<int> NextSOFBatchID { get; set; }
        public Nullable<int> NextStopID { get; set; }
        public Nullable<int> NextDeliveryLogID { get; set; }
        public Nullable<int> NextRouteID { get; set; }
        public Nullable<int> NextAdjustID { get; set; }
        public Nullable<int> NextReasonID { get; set; }
        public Nullable<int> NextOverdueID { get; set; }
        public Nullable<int> NextPostalCodeID { get; set; }
        public int NextStatementID { get; set; }
        public int NextBillCycleID { get; set; }
        public int NextBillCenterID { get; set; }
        public int NextDeliveryGroupID { get; set; }
        public int NextInvPaidID { get; set; }
        public int NextAppliedCrID { get; set; }
        public int NextContactID { get; set; }
        public int NextTaxAuthorityID { get; set; }
        public int NextRecurringID { get; set; }
        public int NextRecurringGroupID { get; set; }
        public int NextEmailLogID { get; set; }
        public int NextImageID { get; set; }
        public int NextPasswordHistoryID { get; set; }
        public int NextCCKeyID { get; set; }
        public int NextCCAuditID { get; set; }
        public int NextCCPaymentContractID { get; set; }
        public int NextGiftTransID { get; set; }
        public int NextReceiptID { get; set; }
        public int NextScanLogID { get; set; }
        public int NextMerchID { get; set; }
        public int NextGiftCardTypeID { get; set; }
        public int NextCampaignID { get; set; }
        public int NextCardBillAutoCreditID { get; set; }
        public int NextClockInAccountID { get; set; }
    }
}
