//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingCycle
    {
        public int BillCycleID { get; set; }
        public int PrintFormID { get; set; }
        public string Description { get; set; }
        public float FinApr { get; set; }
        public decimal MinCharge { get; set; }
        public decimal MinBalance { get; set; }
        public string Message1 { get; set; }
        public string Message2 { get; set; }
        public string Message3 { get; set; }
        public bool Deleted { get; set; }
        public bool CustomStatements { get; set; }
    }
}
