//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardBilling
    {
        public int BilledID { get; set; }
        public int CustomerID { get; set; }
        public int StoreID { get; set; }
        public int InvoiceID { get; set; }
        public int InvType { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public float Pieces { get; set; }
        public decimal Total { get; set; }
        public bool Deleted { get; set; }
        public int EmployeeID { get; set; }
        public bool Processed { get; set; }
        public int SOFBatchID { get; set; }
        public int AutoCreditID { get; set; }
    }
}
