//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCKey
    {
        public int CCKeyID { get; set; }
        public int StoreID { get; set; }
        public string CCKey1 { get; set; }
        public Nullable<System.DateTime> ResetDate { get; set; }
        public int ManagerEmpID { get; set; }
        public int ClerkEmpID1 { get; set; }
        public int ClerkEmpID2 { get; set; }
    }
}
