//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCSetting
    {
        public bool EnableDebitCards { get; set; }
        public bool EnableGiftCards { get; set; }
        public bool EnableCardBillContracts { get; set; }
        public bool EnableCardBillOnPickup { get; set; }
        public bool EnableStatementContracts { get; set; }
        public bool EnableCashContracts { get; set; }
        public bool EnableOfficeContracts { get; set; }
        public bool EnableSkipExpiredCards { get; set; }
        public bool AcceptAmex { get; set; }
        public bool AcceptDiscover { get; set; }
        public bool AcceptJCB { get; set; }
        public bool EnablePcCharge { get; set; }
        public string PcChargeIPAddress { get; set; }
        public int PcChargePort { get; set; }
        public string CardProcessor { get; set; }
        public string CardMerchant { get; set; }
        public string CardBillMerchant { get; set; }
        public bool EnablePaymentGateway { get; set; }
        public string PaymentGatewayCardProcessor { get; set; }
        public string PaymentGatewayDNSPrimary { get; set; }
        public string PaymentGatewayDNSBackup { get; set; }
        public string PaymentGatewayDNSGiftPrimary { get; set; }
        public string PaymentGatewayDNSGiftBackup { get; set; }
        public string PaymentGatewayURLPrimary { get; set; }
        public string PaymentGatewayURLBackup { get; set; }
        public string PaymentGatewayURLCardPassword { get; set; }
        public string PaymentGatewayURLCardBillPassword { get; set; }
        public string PaymentGatewayCardMerchant { get; set; }
        public string PaymentGatewayCardBillMerchant { get; set; }
        public bool EnableBatchClose { get; set; }
        public bool EnableBatchSummary { get; set; }
        public bool EnableMPSBrowse { get; set; }
        public bool EnableE2E { get; set; }
        public bool EnableTokenization { get; set; }
        public bool EnableVoiceAuth { get; set; }
        public string VoiceAuthPhoneMcVisaDisc { get; set; }
        public string VoiceAuthPhoneAmex { get; set; }
        public int ApprovalBatchStationID { get; set; }
        public string DeploymentID { get; set; }
        public string NETePayIPAddress { get; set; }
    }
}
