//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCStationSetting
    {
        public int StationID { get; set; }
        public bool ApproveCredit { get; set; }
        public bool ApproveDebit { get; set; }
        public bool ApproveGift { get; set; }
        public int UserID { get; set; }
        public int CardReaderID { get; set; }
        public int PinPadID { get; set; }
        public int ComPortID { get; set; }
        public int PhysicalDrawers { get; set; }
    }
}
