//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClerkDrawer
    {
        public int ClerkDrawerID { get; set; }
        public int StationID { get; set; }
        public int StoreID { get; set; }
        public string Description { get; set; }
        public int CloseEmpID { get; set; }
        public int OpenEmpID { get; set; }
        public Nullable<System.DateTime> Opened { get; set; }
        public Nullable<System.DateTime> Closed { get; set; }
        public decimal StartingCash { get; set; }
        public decimal Cash { get; set; }
        public decimal Checks { get; set; }
        public decimal Cards { get; set; }
        public decimal Coupons { get; set; }
        public decimal CountedCash { get; set; }
        public decimal CountedChecks { get; set; }
        public decimal CountedCards { get; set; }
        public decimal CountedCoupons { get; set; }
        public int DrawerNumber { get; set; }
        public decimal RemovedCash { get; set; }
        public int OwnerEmpID { get; set; }
        public bool IsPhysicalDrawer { get; set; }
        public decimal CashCount0 { get; set; }
        public decimal CashCount1 { get; set; }
        public decimal CashCount2 { get; set; }
        public decimal CashCount3 { get; set; }
        public decimal CashCount4 { get; set; }
        public decimal CashCount5 { get; set; }
        public decimal CashCount6 { get; set; }
        public decimal CashCount7 { get; set; }
        public decimal CashCount8 { get; set; }
        public decimal CashCount9 { get; set; }
        public decimal CashCount10 { get; set; }
        public decimal CashCount11 { get; set; }
        public decimal CashCount12 { get; set; }
        public decimal CashCount13 { get; set; }
        public decimal CashCount14 { get; set; }
        public decimal CashCount15 { get; set; }
        public decimal CashCount16 { get; set; }
        public decimal Gift { get; set; }
        public decimal CountedGift { get; set; }
    }
}
