//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactID { get; set; }
        public int StoreID { get; set; }
        public int CustomerID { get; set; }
        public int OpenEmpID { get; set; }
        public int CloseEmpID { get; set; }
        public int ContactType { get; set; }
        public string ContactTypeDesc { get; set; }
        public string Issue { get; set; }
        public string Resolution { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public bool Deleted { get; set; }
    }
}
