//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public int StoreID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string Comment { get; set; }
        public bool IsVIP { get; set; }
        public bool FccMember { get; set; }
        public int FccPoints { get; set; }
        public bool NoChecks { get; set; }
        public bool CanBill { get; set; }
        public string ReportCode { get; set; }
        public bool IsTaxExempt { get; set; }
        public string Starch { get; set; }
        public string Package { get; set; }
        public string InvReminder { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> LastOrder { get; set; }
        public Nullable<System.DateTime> LastCashout { get; set; }
        public int BillCycleID { get; set; }
        public string CashReminder { get; set; }
        public int AutoDiscount1ID { get; set; }
        public bool Deleted { get; set; }
        public bool BillToOffice { get; set; }
        public string SOFCardNo { get; set; }
        public string SOFExpDate { get; set; }
        public bool SOFInStore { get; set; }
        public string SOFBatch { get; set; }
        public string EMail { get; set; }
        public bool NoHeatseals { get; set; }
        public bool IsFinCharged { get; set; }
        public string ExtraAccount { get; set; }
        public int BillCenterID { get; set; }
        public decimal CreditLimit { get; set; }
        public int PriceListID { get; set; }
        public bool IsPrintName { get; set; }
        public bool IsHotel { get; set; }
        public bool PrintIReminder { get; set; }
        public bool PrintPackingList { get; set; }
        public string CellPhone { get; set; }
        public string CompanyName { get; set; }
        public bool IsCompany { get; set; }
        public string DLNumber { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public int Language { get; set; }
        public int CoupCount { get; set; }
        public int Designation { get; set; }
        public string LoyaltyID { get; set; }
        public int TaxAuthorityID { get; set; }
        public int InvoicePrintID { get; set; }
        public bool NoEmailPromos { get; set; }
        public bool KioskCannotReplaceCard { get; set; }
        public bool EmailStatements { get; set; }
        public bool PrintStatements { get; set; }
        public string SMSAddress { get; set; }
        public int AccountType { get; set; }
        public int PriceLevel { get; set; }
        public bool RequestsNoEmail { get; set; }
        public string ReadyEmail { get; set; }
        public string StatementEmail { get; set; }
        public string PromoEmail { get; set; }
        public string RouteEmail { get; set; }
        public Nullable<System.DateTime> DiscExpiration { get; set; }
        public string BillLastName { get; set; }
        public string BillFirstName { get; set; }
        public string BillAddr1 { get; set; }
        public string BillAddr2 { get; set; }
        public string BillCity { get; set; }
        public string BillState { get; set; }
        public string BillZip { get; set; }
        public string Notes { get; set; }
        public int InvoiceCopies { get; set; }
        public bool PrintInvoicePrices { get; set; }
        public bool PrintInvoiceTotals { get; set; }
        public bool NoPricesOnFirstCopy { get; set; }
        public bool NoTotalsOnFirstCopy { get; set; }
        public string CampaignCode { get; set; }
        public bool AlwaysEmailReceipts { get; set; }
        public bool InvoicingRestricted { get; set; }
    }
}
