//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryLog
    {
        public int LogID { get; set; }
        public int StoreID { get; set; }
        public int RouteID { get; set; }
        public int CustomerID { get; set; }
        public int InvoiceID { get; set; }
        public int DriverEmpID { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public bool Delivered { get; set; }
        public bool Cashedout { get; set; }
        public Nullable<System.DateTime> CashoutDate { get; set; }
        public bool Deleted { get; set; }
    }
}
