//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftTransaction
    {
        public int GiftTransID { get; set; }
        public int StoreID { get; set; }
        public int CustomerID { get; set; }
        public int EmployeeID { get; set; }
        public int GiftType { get; set; }
        public int GiftClass { get; set; }
        public int GiftClassID { get; set; }
        public string Description { get; set; }
        public decimal Balance { get; set; }
        public string AuthNo { get; set; }
        public string RefNo { get; set; }
        public string GiftNo { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> GiftDate { get; set; }
        public int PaymentID { get; set; }
    }
}
