//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftCardType
    {
        public int GiftCardTypeID { get; set; }
        public int GiftClassID { get; set; }
        public int GiftClass { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public decimal Maximum { get; set; }
        public bool Enabled { get; set; }
        public bool IsNotListed { get; set; }
        public bool IsAwarded { get; set; }
        public bool ListInCashOut { get; set; }
        public bool IsBirthday { get; set; }
        public bool IsPrepaid { get; set; }
        public bool IsSetAmount { get; set; }
        public bool IsDynamicAmount { get; set; }
        public int SortBy { get; set; }
        public bool Deleted { get; set; }
    }
}
