//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heatseal
    {
        public long HeatsealID { get; set; }
        public int CustomerID { get; set; }
        public int GarmentID { get; set; }
        public int ColorID { get; set; }
        public int PatternID { get; set; }
        public int Upcharge1ID { get; set; }
        public int Upcharge2ID { get; set; }
        public int Upcharge3ID { get; set; }
        public int Upcharge4ID { get; set; }
        public int Upcharge5ID { get; set; }
        public int Upcharge6ID { get; set; }
        public int LastInvoice { get; set; }
        public Nullable<System.DateTime> LastInvDate { get; set; }
        public decimal TotalSales { get; set; }
        public int TotalCount { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public bool Deleted { get; set; }
        public int ColorID2 { get; set; }
        public int ColorID3 { get; set; }
        public string Message { get; set; }
    }
}
