//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageLibrary
    {
        public int ImageID { get; set; }
        public string Description { get; set; }
        public string ImageFileName { get; set; }
        public string LinkText { get; set; }
        public string LinkTitle { get; set; }
        public string MergeImageName { get; set; }
        public bool Stretch { get; set; }
        public int PixelWidth { get; set; }
        public int PixelHeight { get; set; }
        public int PercentWidth { get; set; }
        public int PercentHeight { get; set; }
    }
}
