//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int StoreID { get; set; }
        public Nullable<System.DateTime> InventoryDate { get; set; }
        public decimal CSTotalInv { get; set; }
        public decimal STTotalInv { get; set; }
        public decimal ISTotalInv { get; set; }
        public decimal BOTotalInv { get; set; }
        public float CSPcsInv { get; set; }
        public float STPcsInv { get; set; }
        public float ISPcsInv { get; set; }
        public float BOPcsInv { get; set; }
        public decimal CSTotalAR { get; set; }
        public decimal STTotalAR { get; set; }
        public decimal ISTotalAR { get; set; }
        public decimal BOTotalAR { get; set; }
        public float CSPcsAR { get; set; }
        public float STPcsAR { get; set; }
        public float ISPcsAR { get; set; }
        public float BOPcsAR { get; set; }
    }
}
