//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class KioskSetting
    {
        public int StoreID { get; set; }
        public int KioskID { get; set; }
        public string ComSettings { get; set; }
        public int ComPort { get; set; }
        public int TimeOut { get; set; }
        public string IPAddress { get; set; }
        public int Port { get; set; }
        public string HomeTitle { get; set; }
        public string Home1 { get; set; }
        public bool UseSignup { get; set; }
        public bool UseRegistration { get; set; }
        public bool UsePrivacy { get; set; }
        public bool UseAgreement { get; set; }
        public string RegistrationTitle { get; set; }
        public string SignupTitle { get; set; }
        public string Signup1 { get; set; }
        public string PrivacyTitle { get; set; }
        public string Privacy { get; set; }
        public string AgreementTitle { get; set; }
        public string Agreement { get; set; }
        public int StoreColor { get; set; }
        public int PanelColor { get; set; }
        public string TitleFont { get; set; }
        public string PanelFont { get; set; }
        public string LegalFont { get; set; }
        public bool UseWebHomePage { get; set; }
        public string HomeURL { get; set; }
        public string HomeHtmlFilePath { get; set; }
        public bool UseWebSignupPage { get; set; }
        public string SignupURL { get; set; }
        public string SignupHtmlFilePath { get; set; }
        public string Reload { get; set; }
        public string AppOOS { get; set; }
        public string ScanTest { get; set; }
        public string AppClose { get; set; }
    }
}
