//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lot
    {
        public Nullable<int> LotID { get; set; }
        public string Name { get; set; }
        public Nullable<int> StartLot { get; set; }
        public Nullable<int> EndLot { get; set; }
        public Nullable<int> CurrentLot { get; set; }
        public Nullable<int> StartCount { get; set; }
        public Nullable<int> EndCount { get; set; }
        public Nullable<int> CurrentCount { get; set; }
        public string LotColor { get; set; }
        public Nullable<int> CountType { get; set; }
        public bool Deleted { get; set; }
        public int TagStyleID { get; set; }
        public string ForcedStations { get; set; }
        public bool ForceNewLot { get; set; }
        public int CurrentColor { get; set; }
        public bool EnableLotControlRails { get; set; }
        public bool RotateLotColor { get; set; }
        public string Color1 { get; set; }
        public string Color2 { get; set; }
        public string Color3 { get; set; }
        public string Color4 { get; set; }
        public string Color5 { get; set; }
        public string Color6 { get; set; }
        public string Color7 { get; set; }
        public string Color8 { get; set; }
        public string Color9 { get; set; }
        public string Color10 { get; set; }
        public string Color11 { get; set; }
        public string Color12 { get; set; }
        public bool ChangeTagRollColor { get; set; }
    }
}
