//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class MergedCust
    {
        public int FromStoreID { get; set; }
        public int FromCustomerID { get; set; }
        public string FromLName { get; set; }
        public string FromFName { get; set; }
        public int ToStoreID { get; set; }
        public int ToCustomerID { get; set; }
        public string ToLName { get; set; }
        public string ToFName { get; set; }
        public bool CanBill { get; set; }
        public bool BillToOffice { get; set; }
        public bool SOFInStore { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> MergeDate { get; set; }
    }
}
