//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProcess
    {
        public string PlantName { get; set; }
        public string PlantLocation { get; set; }
        public bool IsPlantSent { get; set; }
        public bool IsAlphaRacked { get; set; }
        public bool CreateSBF { get; set; }
        public string SBFPath { get; set; }
        public bool AutoRecSend { get; set; }
        public bool EnableAutoAssembly { get; set; }
        public bool IsPhoneRacked { get; set; }
        public bool UseCRDN { get; set; }
        public string CRDNPath { get; set; }
        public bool UseDCTYD { get; set; }
        public string DCTYDPath { get; set; }
        public bool UsePressed4T { get; set; }
        public string FranchiseeList { get; set; }
        public string FranchiseePasswords { get; set; }
        public int ConveyorSelect { get; set; }
        public bool UseHMCFetch { get; set; }
        public bool UseKioskAndCounter { get; set; }
        public int KioskID { get; set; }
        public int InvoicePrinterID { get; set; }
        public bool UseAutoBagger { get; set; }
        public bool UseBAMStorage { get; set; }
        public bool UseBAMStorageRoutes { get; set; }
        public bool UseBAMStorageCounter { get; set; }
        public bool UseBAMStorageTransfer { get; set; }
        public bool IsMAPBAMStore { get; set; }
        public int BAMCounterArm { get; set; }
        public int BAMRouteArm { get; set; }
        public int BAMTransferArm { get; set; }
        public string BaggerStoreCode { get; set; }
        public int Bagline0 { get; set; }
        public int Bagline1 { get; set; }
        public int Bagline2 { get; set; }
        public int Bagline3 { get; set; }
        public int Bagline4 { get; set; }
        public int Bagline5 { get; set; }
        public bool EnableBaggerBypass { get; set; }
        public bool BypassFoldedShirts { get; set; }
        public int BaggerBypassArm { get; set; }
        public int BAMRouteArm2 { get; set; }
        public int BAMRouteArm3 { get; set; }
        public int BAMRouteArm4 { get; set; }
        public bool EnableFPM { get; set; }
        public int HighestRackLocation { get; set; }
        public bool EnableDropLocker { get; set; }
        public bool IsFPMStore { get; set; }
        public int BagLine6 { get; set; }
        public int BagLine7 { get; set; }
        public int BagLine8 { get; set; }
        public int BagLine9 { get; set; }
        public int BagLine10 { get; set; }
        public int BagLine11 { get; set; }
        public bool UseBAMStorageKiosk { get; set; }
        public int BAMKioskArm { get; set; }
        public bool EnableAPIRouteOrders { get; set; }
        public bool EnableAPIMobileRoute { get; set; }
    }
}
