//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverdueStat
    {
        public int OverdueID { get; set; }
        public int StoreID { get; set; }
        public int OverdueCleanID { get; set; }
        public Nullable<System.DateTime> OverdueDate { get; set; }
        public float OverduePieces { get; set; }
        public decimal OverdueAmount { get; set; }
        public bool Deleted { get; set; }
    }
}
