//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostalCode
    {
        public int PostalCodeID { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode1 { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public bool Deleted { get; set; }
    }
}
