//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public Nullable<int> StoreID { get; set; }
        public string Preference1 { get; set; }
        public string Preference2 { get; set; }
        public string Preference3 { get; set; }
        public string Preference4 { get; set; }
        public string Preference5 { get; set; }
        public string Preference6 { get; set; }
        public string Preference7 { get; set; }
        public string Disclaimer1 { get; set; }
        public string NewCustMessage { get; set; }
        public string Preference8 { get; set; }
        public int HeatsealStyleID { get; set; }
        public string ReceiptMessage { get; set; }
        public string BlankOnWrite { get; set; }
        public string BlankOnCashOut { get; set; }
        public int AllDrawerStationID { get; set; }
        public string Preference9 { get; set; }
        public string ScrollMarquee { get; set; }
        public string TotalDueMarquee { get; set; }
        public string ChangeMarquee { get; set; }
        public string Preference10 { get; set; }
        public string WODisclaimer { get; set; }
        public string Preference11 { get; set; }
        public string BlankEmail { get; set; }
        public string Preference12 { get; set; }
        public string CTDisclaimer { get; set; }
        public decimal PrintCardAgreeOver { get; set; }
        public string DefaultCardBillBatch { get; set; }
    }
}
