//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurgedCust
    {
        public int StoreID { get; set; }
        public int CustomerID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public int EmployeeID { get; set; }
        public bool CanBill { get; set; }
        public bool BillToOffice { get; set; }
        public bool SOFInStore { get; set; }
        public Nullable<System.DateTime> LastOrder { get; set; }
        public Nullable<System.DateTime> LastCashOut { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> PurgeDate { get; set; }
    }
}
