//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int ReceiptID { get; set; }
        public int StoreID { get; set; }
        public int EmployeeID { get; set; }
        public int StationID { get; set; }
        public int CustomerID { get; set; }
        public int AccountType { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public int ReceiptFormID { get; set; }
        public int PaymentID { get; set; }
        public int InvoiceID { get; set; }
        public int CreditID { get; set; }
        public int GiftTransID { get; set; }
        public int NoSaleID { get; set; }
        public string SigString { get; set; }
        public byte[] ReceiptDetailRs { get; set; }
    }
}
