//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurringGroup
    {
        public int RecurringGroupID { get; set; }
        public int StoreID { get; set; }
        public int CustomerID { get; set; }
        public int RecurringID { get; set; }
        public bool Deleted { get; set; }
    }
}
