//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteStop
    {
        public int StopID { get; set; }
        public int CustomerID { get; set; }
        public int RouteID { get; set; }
        public int StopNo { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> StopExpiration { get; set; }
        public string Directions { get; set; }
        public string Notes { get; set; }
        public bool Deleted { get; set; }
        public string DeliveryName { get; set; }
        public string DeliveryAddr1 { get; set; }
        public string DeliveryAddr2 { get; set; }
        public string DeliveryCity { get; set; }
        public string DeliveryState { get; set; }
        public string DeliveryZip { get; set; }
        public bool DMon { get; set; }
        public bool DTue { get; set; }
        public bool DWed { get; set; }
        public bool DThu { get; set; }
        public bool DFri { get; set; }
        public bool DSat { get; set; }
        public bool DSun { get; set; }
        public bool PMon { get; set; }
        public bool PTue { get; set; }
        public bool PWed { get; set; }
        public bool PThu { get; set; }
        public bool PFri { get; set; }
        public bool PSat { get; set; }
        public bool PSun { get; set; }
    }
}
