//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanLog
    {
        public int ScanLogID { get; set; }
        public int StoreID { get; set; }
        public int StationID { get; set; }
        public int ErrorID { get; set; }
        public Nullable<System.DateTime> LogDateTime { get; set; }
        public long InvoiceID { get; set; }
        public string Rack { get; set; }
        public string Description { get; set; }
        public string EmployeeName { get; set; }
        public int Activity { get; set; }
        public bool Download { get; set; }
    }
}
