//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int StoreID { get; set; }
        public int MerchandiseID { get; set; }
        public int SortBy { get; set; }
        public int TaxAuthorityID { get; set; }
        public string Description { get; set; }
        public string SKU { get; set; }
        public decimal Price { get; set; }
        public decimal Cost { get; set; }
        public float ReorderPoint { get; set; }
        public float OnHand { get; set; }
        public int GiftClassID { get; set; }
        public bool IsDiscountable { get; set; }
        public bool Deleted { get; set; }
    }
}
