//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Store1Entities : DbContext
    {
        public Store1Entities()
            : base("name=Store1Entities")
        {
        }
        public Store1Entities(string conn)
            : base(conn)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<AppliedCr> AppliedCrs { get; set; }
        public virtual DbSet<AutoNumber> AutoNumbers { get; set; }
        public virtual DbSet<BillCyclePeriod> BillCyclePeriods { get; set; }
        public virtual DbSet<BillingCenter> BillingCenters { get; set; }
        public virtual DbSet<BillingCycle> BillingCycles { get; set; }
        public virtual DbSet<Campaign> Campaigns { get; set; }
        public virtual DbSet<CardBillAutoCredit> CardBillAutoCredits { get; set; }
        public virtual DbSet<CardBilling> CardBillings { get; set; }
        public virtual DbSet<CCAudit> CCAudits { get; set; }
        public virtual DbSet<CCKey> CCKeys { get; set; }
        public virtual DbSet<CCPaymentContract> CCPaymentContracts { get; set; }
        public virtual DbSet<CCSetting> CCSettings { get; set; }
        public virtual DbSet<CCStationSetting> CCStationSettings { get; set; }
        public virtual DbSet<ClerkDrawer> ClerkDrawers { get; set; }
        public virtual DbSet<ClockInAccount> ClockInAccounts { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Credit> Credits { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DeletedCust> DeletedCusts { get; set; }
        public virtual DbSet<DeliveryCenter> DeliveryCenters { get; set; }
        public virtual DbSet<DeliveryGroup> DeliveryGroups { get; set; }
        public virtual DbSet<DeliveryLog> DeliveryLogs { get; set; }
        public virtual DbSet<EditedCust> EditedCusts { get; set; }
        public virtual DbSet<EmailLog> EmailLogs { get; set; }
        public virtual DbSet<EmployeeDefault> EmployeeDefaults { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<GiftCardType> GiftCardTypes { get; set; }
        public virtual DbSet<GiftTransaction> GiftTransactions { get; set; }
        public virtual DbSet<GLAccount> GLAccounts { get; set; }
        public virtual DbSet<GLJournal> GLJournals { get; set; }
        public virtual DbSet<Heatseal> Heatseals { get; set; }
        public virtual DbSet<ImageLibrary> ImageLibraries { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<InvoiceAdjust> InvoiceAdjusts { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvPaid> InvPaids { get; set; }
        public virtual DbSet<KioskSetting> KioskSettings { get; set; }
        public virtual DbSet<Lot> Lots { get; set; }
        public virtual DbSet<MerchantQTY> MerchantQTies { get; set; }
        public virtual DbSet<MergedCust> MergedCusts { get; set; }
        public virtual DbSet<NoSale> NoSales { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderProcess> OrderProcesses { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Original> Originals { get; set; }
        public virtual DbSet<OverdueStat> OverdueStats { get; set; }
        public virtual DbSet<PasswordHistory> PasswordHistories { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Physical> Physicals { get; set; }
        public virtual DbSet<PostalCode> PostalCodes { get; set; }
        public virtual DbSet<Preference> Preferences { get; set; }
        public virtual DbSet<PurgedCust> PurgedCusts { get; set; }
        public virtual DbSet<Reason> Reasons { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<RecurringGroup> RecurringGroups { get; set; }
        public virtual DbSet<Recurring> Recurrings { get; set; }
        public virtual DbSet<RouteItem> RouteItems { get; set; }
        public virtual DbSet<RouteStop> RouteStops { get; set; }
        public virtual DbSet<SalesTax> SalesTaxes { get; set; }
        public virtual DbSet<ScanLog> ScanLogs { get; set; }
        public virtual DbSet<SOFBatch> SOFBatches { get; set; }
        public virtual DbSet<StatementBalance> StatementBalances { get; set; }
        public virtual DbSet<StatementHistory> StatementHistories { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<TaxAuthority> TaxAuthorities { get; set; }
        public virtual DbSet<TimeCard> TimeCards { get; set; }
        public virtual DbSet<Version> Versions { get; set; }
        public virtual DbSet<WirelessCarrier> WirelessCarriers { get; set; }
    }
}
