//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Nullable<int> StoreID { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public string ModemNumber { get; set; }
        public string FaxNumber { get; set; }
        public string EMailAddress { get; set; }
        public Nullable<int> MaxDrycleanPieces { get; set; }
        public Nullable<int> MaxLaundryPieces { get; set; }
        public int CountryID { get; set; }
        public bool StretchLogo { get; set; }
        public string LogoPath { get; set; }
        public int PrintFormID { get; set; }
        public string RegistrationNo { get; set; }
        public int PrintSidesID { get; set; }
        public bool PaymentsFirst { get; set; }
        public string StName { get; set; }
        public string StAddress1 { get; set; }
        public string StAddress2 { get; set; }
        public string StCity { get; set; }
        public string StState { get; set; }
        public string StZipCode { get; set; }
        public string StPhoneNumber { get; set; }
        public string StFaxNumber { get; set; }
        public string StRegistrationNo { get; set; }
        public string StoreHours { get; set; }
        public string StStoreHours { get; set; }
        public string CardMerchant { get; set; }
        public string CardBillMerchant { get; set; }
        public string DebitMerchant { get; set; }
        public string GiftMerchant { get; set; }
        public string CardProcessor { get; set; }
        public string DebitProcessor { get; set; }
        public string GiftProcessor { get; set; }
        public int StoreColor { get; set; }
        public string WebSite { get; set; }
        public string WebSiteText { get; set; }
        public string WebSiteTitle { get; set; }
        public string ImageFolder { get; set; }
        public string WebSiteImageFolder { get; set; }
        public int InvoiceImageID { get; set; }
        public int StatementImageID { get; set; }
        public int CAIntegrationType { get; set; }
        public string CAIPAddress { get; set; }
        public int CAPort { get; set; }
    }
}
