//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeCard
    {
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> ClockIn { get; set; }
        public Nullable<System.DateTime> Clockout { get; set; }
        public string WorkType { get; set; }
        public bool Deleted { get; set; }
        public int TimeCardID { get; set; }
        public string AccountNumber { get; set; }
    }
}
