//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EFStuff.Stores
{
    using System;
    using System.Collections.Generic;
    
    public partial class WirelessCarrier
    {
        public int WirelessID { get; set; }
        public int SortBy { get; set; }
        public string Company { get; set; }
        public string TextAddress { get; set; }
    }
}
